name: dapr.cqrs

extensions:
- name: zipkin
- name: dapr
  components-path: "\"./components\""
  config: app-config
  log-level: info
  exclude-placement-container: true
#  placement-port: 6050

# The name will be used as the app-id. For a .NET project, Tye only needs the path to the project file.
services:

# WRITE LAYER

- name: api-write
  project: Dapr.Cqrs.Api.Write/Dapr.Cqrs.Api.Write.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  tags:
    - write
    - ui
  bindings:
    - port: 1080
      containerPort: 80

- name: transactional-outbox
  project: Dapr.Cqrs.TransactionalOutbox/Dapr.Cqrs.TransactionalOutbox.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  tags:
    - write
    - ui
  bindings:
    - port: 2080
      containerPort: 80

- name: signalr-hub
  project: Dapr.Cqrs.Hubs/Dapr.Cqrs.Hubs.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  bindings:
      - port: 3080
        containerPort: 80
  tags:
    - write  
    - read  
    - ui

# PROCESSOR LAYER

- name: processor-search
  project: Dapr.Cqrs.Processor.Search/Dapr.Cqrs.Processor.Search.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  bindings:
      - port: 4080
        containerPort: 80
  tags:
    - read  
    - processor

- name: processor-time
  project: Dapr.Cqrs.Processor.Time/Dapr.Cqrs.Processor.Time.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  bindings:
      - port: 5080
        containerPort: 80
  tags:
    - read  
    - processor
    - ui

- name: processor-raw
  project: Dapr.Cqrs.Processor.Raw/Dapr.Cqrs.Processor.Raw.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  bindings:
      - port: 6080
        containerPort: 80
  tags:
    - read  
    - processor
    - ui
# UI LAYER

- name: api-read
  project: Dapr.Cqrs.Api.Read/Dapr.Cqrs.Api.Read.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  tags:
    - processor
    - read
    - ui
  bindings:
    - port: 7080
      containerPort: 80

# UI LAYER

- name: ui
  project: Dapr.Cqrs.UI/Dapr.Cqrs.UI.csproj
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  tags:
    - read
    - ui
  bindings:
    - port: 9080
      containerPort: 80


# Containers you want to run need an image name and set of ports to expose.

- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - name: rabbit
      connectionString: amqp://guest:guest@localhost:${port}
      protocol: amqp
      port: 5672
  tags:
    - ui
    - write
    - read
    - processor

- name: sqlserver
  image: sqlserver-dapr
  bindings:
  - connectionString: Server=${host},${port};Database=explorer;User ID=sa;Password=${env:SA_PASSWORD}
    containerPort: 1433
    port: 31433
  env:
  - name: ACCEPT_EULA
    value: "y"
  - name: SA_PASSWORD
    value: Password1!
  tags:
    - ui
    - write
    - read
    - processor

- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}" 
  tags:
    - ui
    - write
    - read
    - processor

- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
  tags:
    - ui
    - write
    - read
    - processor

- name: azurite
  image: mcr.microsoft.com/azure-storage/azurite
  bindings:
    - name: blobs
      port: 10000
      containerPort: 10000
      protocol: http
      connectionString: BlobEndpoint=${protocol}://${host}:${port}/devstoreaccount1;DefaultEndpointsProtocol=${protocol};AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
    - name: tables
      port: 10002
      containerPort: 10002
      protocol: http
      connectionString: TableEndpoint=${protocol}://${host}:${port}/devstoreaccount1;DefaultEndpointsProtocol=${protocol};AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
  tags:
    - ui
    - write
    - read
    - processor
