apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: outbox-send
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 1s"
scopes:
  - transactional-outbox